# Generated by Django 5.2.15 on 2026-07-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_document_status_alter_meeting_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expected_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('CHANGES_REQUESTED', 'Changes Requested'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('MILESTONE_TRACKING', 'Milestone Tracking'), ('DOCUMENT_SUBMISSION', 'Document Submission'), ('REVIEW_MEETING', 'Review Meeting'), ('FINAL_REPORT_SUBMISSION', 'Final Report Submission'), ('VIVA_SCHEDULED', 'Viva Scheduled'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=50),
        ),
    ]
